
spring.datasource.url=jdbc:mysql://localhost:3306/project_united?useSSL=false&createDatabaseIfNotExist=true

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.show_sql=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.type=TRACE